[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://api.nachoaveragecart.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
